// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"HydraServer/chatserver/services"
	"HydraServer/pkg/redisbackend"
	"github.com/topfreegames/pitaya/v2"
)

// Injectors from wire.go:

func BuildInjector(pitayaPitaya *pitaya.Pitaya, redisBackend *redisbackend.RedisBackend) (*Injector, func(), error) {
	chat := services.NewChatService(pitayaPitaya, redisBackend)
	injector := &Injector{
		ChatService: chat,
		App:         pitayaPitaya,
	}
	return injector, func() {
	}, nil
}
