// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"HydraServer/gateserver/models"
	"HydraServer/httpserver/controller"
	"HydraServer/httpserver/logic"
	"github.com/sirupsen/logrus"
	"github.com/topfreegames/pitaya/v2/cluster"
)

import (
	_ "HydraServer/httpserver/docs"
)

// Injectors from wire.go:

func BuildInjector(serviceDiscovery cluster.ServiceDiscovery, fieldLogger logrus.FieldLogger) (*Injector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	userInfoRepo := &models.UserInfoRepo{
		DB: db,
	}
	userLogic := &logic.UserLogic{
		UserInfoRepo: userInfoRepo,
	}
	accountController := &controller.AccountController{
		UserLogic:        userLogic,
		ServiceDiscovery: serviceDiscovery,
	}
	injector := &Injector{
		AccountController: accountController,
		ServiceDiscovery:  serviceDiscovery,
	}
	return injector, func() {
		cleanup()
	}, nil
}
