// Code generated by error-gen. DO NOT EDIT.
package constant

const (
    UserNotInConnect = -2                        // 链接没有找到用户
    RoleNotInConnect = -1                        // 链接没有找到角色
    OK = 0                                       // 成功
    InvalidParam = 1                             // 参数有误
    DBError = 2                                  // 数据库异常
    UserExist = 3                                // 用户已存在
    PwdIncorrect = 4                             // 密码不正确
    UserNotExist = 5                             // 用户不存在
    TokenInvalid = 6                             // Token无效
    HardwareIncorrect = 7                        // Hardware错误
    RoleAlreadyCreate = 8                        // 已经创建过角色了
    RoleNotExist = 9                             // 角色不存在
    RoleNameExist = 10                           // 昵称已经存在
    GenerateTokenFail = 11                       // 生成toke失败
    ParseTokenFail = 12                          // 解析toke失败
    ReLoginFail = 13                             // 重新登录失败
    LoginExpired = 14                            // 登录已过期，请重新登录
    NoServersAvailable = 15                      // 没有服务器可用
    ServerBusy = 16                              // 服务器繁忙
)