// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/sirupsen/logrus"
	"github.com/topfreegames/pitaya/v2"
	"HydraServer/gateserver/models"
	"HydraServer/gateserver/services"
)

// Injectors from wire.go:

func BuildInjector(pitayaPitaya *pitaya.Pitaya, fieldLogger logrus.FieldLogger) (*Injector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	userInfoRepo := &models.UserInfoRepo{
		DB: db,
	}
	loginLastRepo := &models.LoginLastRepo{
		DB: db,
	}
	account := services.NewAccountService(pitayaPitaya, userInfoRepo, loginLastRepo)
	injector := &Injector{
		AccountService: account,
		App:            pitayaPitaya,
	}
	return injector, func() {
		cleanup()
	}, nil
}
